#!/bin/bash

# enter your login and password
ITC_LOGIN=''
ITC_PASS=''

PLATFORM_VER='8.3.18.1363'

login_url='https://login.1c.ru/login'
dl_url="https://releases.1c.ru/version_file?nick=Platform83&ver=$PLATFORM_VER&path=Platform\\${PLATFORM_VER//./_}\\deb64_${PLATFORM_VER//./_}.tar.gz"
echo "Download from: $dl_url"

echo 'Logging in...'
curl -s -k -c ccc1.tmp "$login_url" | sed -n '/execution/{s/.*name="execution" \+value="\([a-zA-Z0-9_\-]\+\)"\/>.*/\1/;p}' > ex.tmp
curl -k -b ccc1.tmp -c ccc2.tmp -d "username=$ITC_LOGIN&password=$ITC_PASS&_eventId=submit" --data-urlencode execution@ex.tmp "$login_url"
rm -f ex.tmp

# outdated download code - not working
#echo 'Downloading file...'
#curl -# -L -b ccc2.tmp -o deb64.tar.gz "$dl_url"

# 18.02.21 !latest download code here
echo 'Obtaining link to file...'
curl -# -L -b ccc2.tmp "$dl_url" | sed -n '/Скачать дистрибутив/{s/.*<a href="\(https:[a-zA-Z0-9_\/\.\-]\+\)">.*/\1/;p;q}' > link.tmp
echo 'Downloading file...'
xargs -n 1 curl -# -L -b ccc2.tmp -o deb64.tar.gz < link.tmp

rm -f ccc1.tmp ccc2.tmp
rm -f link.tmp

