#!/bin/bash

# network for wispa host -- vmware hosts must use ipvlan
#docker network create -d macvlan --subnet=10.0.0.0/10 --gateway=10.15.0.1 --ip-range=10.14.75.32/28 -o parent=eth0 uwcnet

#  --network uwcnet --ip 10.15.0.13
docker run -d --name faq-uwc \
  --hostname faq --domainname uwc.ufanet.ru \
  -p 81:80 -p 444:443 \
  -v /srv/dokuwiki/conf:/dokuwiki/conf \
  -v /srv/dokuwiki/data:/dokuwiki/data \
  -v /etc/ssl/certs/uwc.ufanet.ru.pem:/etc/ssl/certs/u.pem:ro \
  -v /etc/ssl/private/uwc.ufanet.ru-key.pem:/etc/ssl/private/u.key:ro \
  -e TZ=Asia/Yekaterinburg \
  uralm1/faq-uwc
