#!/bin/bash

# network for wispa host -- vmware hosts must use ipvlan
#docker network create -d macvlan --subnet=10.0.0.0/10 --gateway=10.15.0.1 --ip-range=10.14.75.32/28 -o parent=eth0 uwcnet

docker run -d --name ovpn --network uwcnet --ip 10.14.72.2 \
  --hostname ovpn --domainname uwc.local \
  -v /srv/ovpn:/etc/openvpn \
  -p 1194:1194/udp \
  -e TZ=Asia/Yekaterinburg \
  --cap-add=NET_ADMIN \
  uralm1/openvpn
